### PR TITLE
Added joins functionality

### PR DESCRIPTION
**Pull request by nmc9**
Added methods to the Filter.php file to allow filters to join from other tables.
Also included testCases and stubs for further testing of the join functions

### CODE REVIEW

**Comment by Kyslik** [comment]
Could you explain what is the rationale behind the PR, in the filter itself you have Builder instance available so stock `->join()` work.

**Comment by nmc9** [comment]
Sorry i should have more clear about what I actually did. Yes you can use the join methods in the builder but it can cause some problems.
The main reason for having the join in the filter class is for situations like this:
If you have multiple fields on a joined table (like created_at, updated_at) if you try to set them up as separate filters the join duplicates. When it comes time to build the query you end up with multiple joins to the same table. 
For Example a setup like this:
```
public function usercreatedat($created_at){
    return $this->getBuilder()->join("user","user.id","role.user_id")
    ->where("user.created_at",$created_at);
}

public function userupdatedat($updated_at){
    return $this->getBuilder()->join("user","user.id","role.user_id")
    ->where("user.updated_at",$updated_at);
}
```
Would produce this:

> select * **inner join "user"** on "user"."id" = "role"."user_id" **inner join "user"** on "user"."id" = "role"."user_id" where "user"."created_at" = '2018-08-13 12:33:05' and "user"."updated_at" = '2018-08-13 12:33:05'

So i added a check in the filter table that only adds the join if it's not already in the builder.

Also another option if you are worried about muddying up the Filter class would be to extend it with a JoinableFilter class. Just a thought

**Comment by Kyslik** [comment]
Makes sense, I will have to dig in to this :) and figure how best it would be, thank you for contribution.

**Comment by Kyslik** [comment]
@nmc9 
I added trait JoinSupport that adds the methods you've created, but they all accept signatures like `Builder::join(...)|leftJoin(...)|rightJoin(..,)`, even closures etc. Tests are unchanged (the queries themselves) so I hope I did not cripple any functionality. 

I will have to work on readme.

**Pull request merged**
